import os

BASE_DIR = os.path.abspath(os.path.dirname(__file__))


class Config:
    SQLALCHEMY_DATABASE_URI = "sqlite:///" + os.path.join(
        BASE_DIR, "..", "metalwolft.db"
    )
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    JWT_SECRET_KEY = "metalwolft_super_secret_jwt_key_2026_secure"
    JWT_ALGORITHM = "HS256"

    GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")

    DEFAULT_CURRENCY = "EUR"

    DEFAULT_MIN_WIDTH_CM = 40
    DEFAULT_MAX_WIDTH_CM = 240
    DEFAULT_MIN_HEIGHT_CM = 40
    DEFAULT_MAX_HEIGHT_CM = 240

    FREE_SHIPPING_THRESHOLD = 150
    BASE_SHIPPING_FEE = 17

    OVERSIZE_SIDE_THRESHOLD_CM = 175
    OVERSIZE_SUM_THRESHOLD_CM = 300
    OVERSIZE_SUM_MAX_THRESHOLD_CM = 400

    OVERSIZE_SIDE_SURCHARGE = 49
    OVERSIZE_SUM_SURCHARGE = 49
    OVERSIZE_SUM_MAX_SURCHARGE = 99

    STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")
    STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET")
    STRIPE_SUCCESS_URL = "http://localhost:3000/success"
    STRIPE_CANCEL_URL = "http://localhost:3000/cancel"

    CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
    CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
    CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")
