"""create products table

Revision ID: c731cdb5fd35
Revises: 
Create Date: 2026-01-27 17:49:35.861959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c731cdb5fd35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.Enum('fijas', 'abatibles', 'correderas', name='product_category'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('seo_h1', sa.String(length=180), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('is_new', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('main_image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
